### ISSUE TITLE
ERROR  Cannot restart nuxt:  nuxtCtx.tryUse is not a function

### ISSUE THREAD

**Issue by avxkim** [vueuse/schema-org#17]
`"nuxt": "^3.0.0-rc.4"` causes an error: "ERROR  Cannot restart nuxt:  nuxtCtx.tryUse is not a function"

followed instructions: https://vue-schema-org.netlify.app/guide/setup/nuxt.html#install

When i add this module in to nuxt.config.ts:

```
  modules: [
    'nuxt-schema-org',
  ],
```

i get the above error

**Comment by harlan-zw** [comment]
Hey @avxkim 

This is breaking change for modules which are using the latest @nuxt/kit with earlier versions of the nuxt RC. You should try using `3.0.0-rc.4`

**Comment by harlan-zw** [comment]
Also you may need to do `nuxi upgrade --force` and / or delete your lock file / node_modules.

**Comment by avxkim** [comment]
@harlan-zw thanks, i have issues when doing `npx nuxi-edge@latest upgrade --force` in a monorepo (with yarn). In a normal project with npm, it goes well.

**Comment by harlan-zw** [comment]
Going to close this off as this is a nuxt RC issue, feel free to re-open if you are still stuck
