### ISSUE TITLE
support placing json-ld at the end of body

### ISSUE THREAD

**Issue by markmartirosian** [vueuse/schema-org#18]
References:

https://github.com/ampproject/amphtml/issues/1976
[Yes, you can add JSON structured data to the body of your pages](https://searchengineland.com/yes-you-can-add-json-structured-data-to-the-body-of-your-pages-321870)

**Comment by harlan-zw** [comment]
Hey @markmartirosian 

This is the default behaviour of v1, which is currently available in beta.

**Comment by harlan-zw** [comment]
As v1 is now [released ](https://vue-schema-org.netlify.app/posts/v1-release), I'll close this off.
