### ISSUE TITLE
autoImports:sources is deprecated in nuxt 3.0.0-rc.9

### ISSUE THREAD

**Issue by thijsw** [vueuse/schema-org#23]
When I use this package in a Nuxt 3.0.0-rc.9 project I get a warning that the hook `autoImports:sources` is deprecated:

```
 WARN  autoImports:sources hook is deprecated. Use imports:sources with nuxt>=3.0.0-rc.9
```

**Comment by harlan-zw** [comment]
Hey, thanks for flagging.

Should be fixed

**Comment by thijsw** [comment]
Thank you, that was quick!
