### ISSUE TITLE
SourceMap point to missing source files with RC13

### ISSUE THREAD

**Issue by BenjaminOddou** [vueuse/schema-org#29]
Hello @harlan-zw,

I remarked that since nuxt RC-13 update, I had this warning related to schema-org plugin :

```sh
⚠️ WARN  Sourcemap for "/Users/User/Documents/portfolio/node_modules/nuxt-schema-org/dist/runtime/plugin.mjs" points to missing source files
```

Latest version of the plugin :

```json
{
    "nuxt-schema-org": "^1.1.0-beta.5",
}
```

EDIT : warning is ocurring when running `npm run dev` command

**Comment by samanar** [comment]
same problem here . any ideas ??

**Comment by SebastianBoergers** [comment]
Same Issue here when upgrading from RC12 to 13.

**Comment by Peggy535** [comment]
Snap - went from rc-12 to rc-13 yesterday. I uninstalled/re-installed the module but this didn't work. I had to do that with the tailwind module yesterday which seemed to fix a glitch? Puzzling...

**Comment by harlan-zw** [comment]
Hey, thanks for reporting this.

Please ignore until a fix is ready, which will likely be a week or so (doing some updates with @vueuse/head)

**Comment by Peggy535** [comment]
Awesome, thanks! The module is brilliant btw. Really amazing work, it's so helpful.

A bit of a temporary 'hacky' solution but okay for the meantime if you're needing to test/ be in a dev environment. I looked at the package.json file for the nuxt-schema-org node module and updated @nuxt/kit and @nuxt/schema to 3.0.0-rc.13 from 3.0.0-rc.11. This seems to work and produce the correct schema on my rendered pages when running npm run dev. I still get the warning, but it produces the correct schema.

**Comment by harlan-zw** [comment]
This should be resolved with v2. Let me know if you have any issues with the migration
