### ISSUE TITLE
docs: `useSchemaOrg()` doesn't seem to be reactive?

### ISSUE THREAD

**Issue by michealroberts** [vueuse/schema-org#30]
I'm wondering what the usage is for the `useSchemaOrg` because I can't seem to get a reactive change to occur.

A typical example of usage I have provided is the following:

```ts
import type { Ref } from 'vue'

import type { Product } from '@/types'

export const useProductJSONLD = (product: Ref<Product | undefined>) => {
  useSchemaOrg([
    defineProduct({
      name: computed(() => product.value?.title || ''),
      description: computed(() => product.value?.description || ''),
      sku: computed(() => product.value?.id || ''),
    })
  ]) 
}
```

However, the output seems to take from the default that looks to be provided in the head section of the nuxt.config.ts file:

<img width="703" alt="Screenshot 2022-11-12 at 16 57 39" src="https://user-images.githubusercontent.com/84131395/201485443-149be2e3-4cc6-446e-af2a-963827ec25eb.png">

Would it help if the input was made to be a `MaybeComputedRef` type ... ? I would be happy to PR for this.

Caveat - I'm using the Nuxt 3 module.

**Comment by harlan-zw** [comment]
Hey @michealroberts 

Thanks for the issue. Not too sure what's going on here for the reactivity not to work.

With the release of @vueuse/head I'll be able to improve the reactivity quite a bit, so will look into this in the next week or so

**Comment by harlan-zw** [comment]
With the v2 release, all reactivity issues should be resolved.

Let me know if you have any issues with it
