### ISSUE TITLE
Nuxt 3 Stable errors

### ISSUE THREAD

**Issue by urbangeekllc** [vueuse/schema-org#34]
Currently just switched from rc8 to stable schema-org was working just fine but now it's not working at all  after switching to stable.
![image](https://user-images.githubusercontent.com/113277133/203658880-cceb8b70-c6e8-4c4e-8eb5-52814fe4f100.png)

![image](https://user-images.githubusercontent.com/113277133/203659908-8dc69f25-d069-4356-9e6b-171e856270c0.png)

Running "nuxt-schema-org": "^1.1.0-beta.6"

**Comment by sigliblog** [comment]
same problem here... 

any update... ???

**Comment by urbangeekllc** [comment]
No nothing yet. Hoping to hear something soon on this issue. Did you
upgrade to Nuxt 3 Stable as well?

**Comment by harlan-zw** [comment]
Hey guys, thanks for reporting. Will try and resolve soon

**Comment by koronowicz** [comment]
Same problem after build (nuxt rc13), working well in dev

**Comment by harlan-zw** [comment]
I am currently working on a v2 that utilizes the new @vueuse/head v1 API. Will be released possibly tomorrow.

**Comment by urbangeekllc** [comment]
@harlan-zw  thank you for the update. Can't wait to check out V2

**Comment by harlan-zw** [comment]
Thanks for your patience, the v2 is out and release notes are here: https://github.com/vueuse/schema-org/releases/tag/v2.0.0

For the nuxt module, it should be pretty straight forward, just update to 2.0.0.

 If you do have issues, try deleting lock file / node_modules and re-installing. 2.0.0 requires the latest @vueuse/head which Nuxt has pinned but you may be using an old version.

Will close for now but please post if you have any issues

**Comment by urbangeekllc** [comment]
Thank you Harlan that fixed the issue for me. Everything is working fine now
