### ISSUE TITLE
No items detected  rich results testing 

### ISSUE THREAD

**Issue by sigliblog** [vueuse/schema-org#35]
No items detected
No rich results detected in this URL. [Learn more]

only `defineOrganization({})` detected 

No items detected in google  rich results testing 
`  defineWebSite({}),`
`  defineWebPage(),`

**Comment by harlan-zw** [comment]
Hi @sigliblog 

Google does not provide rich results for WebPage or WebSite as far as I'm aware, however they are added as best practice. You can confirm the schema is added correctly using https://validator.schema.org/
