### ISSUE TITLE
Non reactive debugger

### ISSUE THREAD

**Issue by jcdb95** [vueuse/schema-org#36]
I've been trying to use the debugger to test a FAQ page, but for some reason, once you refresh the page, it breaks and is also not reactive.

For example: Let's imagine I want to have a list of FAQs, and I want the answer to the question to contain a dynamic value (a random one, just for testing, but eventually it can be an API call).

## My code will look something like this:

```
<script setup>
import { SchemaOrgDebug, SchemaOrgQuestion } from "@vueuse/schema-org/runtime";
import { computed } from "vue";

const questions = computed(() => {
  return [
    {
      question: "Question 1",
      answer: `Answer ${String(Math.round(Math.random() * (10 - 0) + 0))}`,
    },
    {
      question: "Question 2",
      answer: `Answer ${String(Math.round(Math.random() * (10 - 0) + 0))}`,
    },
    {
      question: "Question 3",
      answer: `Answer ${String(Math.round(Math.random() * (10 - 0) + 0))}`,
    },
    {
      question: "Question 4",
      answer: `Answer ${String(Math.round(Math.random() * (10 - 0) + 0))}`,
    },
  ];
});
</script>

<template>
    <SchemaOrgDebug />
    <SchemaOrgQuestion
      v-for="faq in questions"
      :key="faq.answer"
      :name="faq.question"
      :accepted-answer="faq.answer"
    >
    </SchemaOrgQuestion>

    <ul>
      <li v-for="faq in questions" :key="faq.answer">
        {{ faq.question }}
        <br />
        {{ faq.answer }}
        <hr />
      </li>
    </ul>
</template>

```

The render list shows something different every time I hit refresh on the page, but the debugger many times disappears, or is not fully reactive to the random values of the answer. Am I missing something? Does it has to contain a `key` to re-render?

Here is a repo where I set up the example: [Repo](https://github.com/jcdb95/non-reactive-debugger)

Thanks!

**Comment by harlan-zw** [comment]
Thanks for the reproduction! I did some testing with v2 and the issue seems to be resolved, would you mind testing?
