### ISSUE TITLE
FAQ schema: Google Search Console error: missing field mainEntity

### ISSUE THREAD

**Issue by koronowicz** [vueuse/schema-org#39]
I've got this critical error from Google Search Console:

> Missing fields „mainEntity”

This is my schema:

```
<SchemaOrgOrganization name="Name" logo="/logo.png" />
<SchemaOrgWebSite name="Name" />
<SchemaOrgWebPage />
<SchemaOrgWebPage type="FAQPage" />
<SchemaOrgQuestion :name="q.question" :accepted-answer="q.answer" />
```

**Comment by koronowicz** [comment]
Ok, solved, you cannot use double tags.
```
<SchemaOrgWebPage />
<SchemaOrgWebPage type="FAQPage" />
```

**Comment by chemeng** [comment]
@koronowicz  I"m facing the same issue. What do you need by "double tags" ?

**Comment by koronowicz** [comment]
@chemeng In my layout I used 
```
<SchemaOrgWebPage />
```
and in a component when I used Question I also added:
```
<SchemaOrgWebPage type="FAQPage" />
```
that result in no reference in Question via mainEntity to WebPage.

Did that help?

**Comment by chemeng** [comment]
I see, so you had a "duplicate" tag.. Doesn't look like this is the case for us.. Thank you though!
