### ISSUE TITLE
Always empty schema on Nuxt 3.2.2 and nuxt-schema-org 2.1.1

### ISSUE THREAD

**Issue by Yohaeg** [vueuse/schema-org#40]
Hi,
I tried to use the package version 2.1.1 on Nuxt 3.2.2 but always got an empty schema.
I tried Composition API and Component API but always got the same result empty schema.

When I try with package version 1.1.0-beta.1 with Nuxt 3.0.0 usually works.

![image](https://user-images.githubusercontent.com/2530850/221429529-a630b2aa-97df-4072-a1d3-81335d108d09.png)

is it a known issue on these versions?

**Comment by harlan-zw** [comment]
Hey @Yohaeg, thanks for the issue.

Looks like a compatibility issue. I've pushed up version 2.1.2 which may fix it.

Otherwise please wait for the next Nuxt patch will include an updated Unhead.

**Comment by Yohaeg** [comment]
Hey @harlan-zw, 
It's working now thank you
