### ISSUE TITLE
Event schema node development?

### ISSUE THREAD

**Issue by cyruscollier** [vueuse/schema-org#8]
Does anyone have an idea of when the Event node will be available in this library? The docs say it's in development, but I don't see it anywhere in the repo. I need to implement the Event schema in a Nuxt 3 app that's going into production soon. If work hasn't begun on it yet, I'd be happy to implement Event myself and submit a PR for it. It doesn't look too time-consuming to add the spec and test files for a new schema node.

**Comment by harlan-zw** [comment]
Hey @cyruscollier 

I'm on leave at the moment, happy to look into this when I'm back and settled (2 weeks)

Otherwise please free to submit a PR 🙂

**Comment by harlan-zw** [comment]
Hey @cyruscollier 

Sorry for the long lead time on this, I've just finished up [v1](https://vue-schema-org.netlify.app/posts/v1-release) with the Event node included

Going to close this off, but if you any issues or such please re-open.

Thanks again for the contribution!

**Comment by cyruscollier** [comment]
Awesome!
