### ISSUE TITLE
Nuxt module improvements

### ISSUE THREAD

**Issue by pi0** [vueuse/schema-org#9]
Hi @harlan-zw and thanks for nice Nuxt module! Following up [#374](https://github.com/nuxt/modules/pull/374), I've made a quick review over the code and here are some improvement suggestions:

-  With hybrid rendering, both SSR and SPA modes can happen. Please avoid to depend on `ssr` option to conditionally inject plugin [here](https://github.com/vueuse/schema-org/blob/f69ac4da92a9c61afe8c8db51c594906fe2144e1/packages/nuxt/src/module.ts#L47). You can use runtime logic and `serverRendered` flag in the payloadto make a difference in the behavior
- Since `@vueuse/schema-org` is an implicit dependency for Nuxt users (they install `nuxt-schema-org`), I would make an alias for `@vueuse/schema-org` to it's full path to avoid unwanted behavior with different package managers

**Comment by harlan-zw** [comment]
Hey @pi0 

Appreciate the time in looking over the module, thanks! I've [fixed up](https://github.com/vueuse/schema-org/commit/4fac56a2531d98660b10410845fc4d5c842bb373) the first issue you mentioned, it makes a lot more sense to do it like this.

Would you mind elaborating on what you mean by the second point? I understand the issue but not too sure what you're recommending as the fix.

I tried something this but it ended up throwing a lot of errors, seemingly the import breaks.

```ts
const { resolve } = createResolver(import.meta.url)
nuxt.options.alias['@vueuse/schema-org'] = resolve('@vueuse/schema-org')
```

**Comment by pi0** [comment]
The naming might be confusing but resolve is similar to `path.resolve` (`await resolver.resolvePath` is the one you are looking for)

**Comment by harlan-zw** [comment]
Ah of course, thanks. 

I've added the alias, I had an error when it was resolving to the `index.cjs` file, so I changed it to resolve to the `dist` directory. 

```
[nuxt] [request error] Object.defineProperty called on non-object
  at Function.defineProperty (<anonymous>)  
  at $id_16230e0f (./.nuxt/dist/server/server.mjs:3011:8)  
  at __instantiateModule__ (./.nuxt/dist/server/server.mjs:6319:9)  
  at __ssrLoadModule__ (./.nuxt/dist/server/server.mjs:6257:25)  
  at ssrImport (./.nuxt/dist/server/server.mjs:6282:13)  
  at $id_a3506958 (./.nuxt/dist/server/server.mjs:2982:37)  
  at async __instantiateModule__ (./.nuxt/dist/server/server.mjs:6319:3)
```

Testing it seemed all good, but do you forsee any issues? https://github.com/vueuse/schema-org/commit/bca8fea37c7810b439ba3f78256592e531356dae#diff-be7ecc6bc17358942938e025d26bee5e5c3664db77e2be717b644d96d3222172R52

**Comment by harlan-zw** [comment]
Going to close this off as all the above issues were resolved, although have now been superseded by [v1](https://vue-schema-org.netlify.app/posts/v1-release).

If you want to review the latest module, that would be awesome, but understand if you have limited capacity.
